language: php

jobs:
  include:
    - php: "7.0"
      env: SYMFONY_VERSION=3.4
    - php: "7.1"
      env: SYMFONY_VERSION=3.4
    - php: "7.1"
      env: SYMFONY_VERSION=4.4
    - php: "7.2"
      env: SYMFONY_VERSION=4.4
    - php: "7.3"
      env: SYMFONY_VERSION=4.4
    - php: "7.1"
      env: SYMFONY_VERSION=5.0
    - php: "7.2"
      env: SYMFONY_VERSION=5.0
    - php: "7.3"
      env: SYMFONY_VERSION=5.0
    - php: "7.4"
      env: SYMFONY_VERSION=5.0

install:
  - composer require symfony/config:"^$SYMFONY_VERSION" symfony/http-kernel:"^$SYMFONY_VERSION" symfony/routing:"^$SYMFONY_VERSION" symfony/dependency-injection:"^$SYMFONY_VERSION"
  - composer install

script:
  - composer lint
  - composer test
